In [1]:
import numpy as np

In [2]:
# Broadcasting
a = np.ones((3, 5))     # a.shape = (3, 5)
b = np.ones((5,))       # b.shape = (5,)

# thêm 1 vào shape nhỏ hơn, thêm vào shape của b (1, 5), do 5 ở axis cuối, nêm thêm 1 vào axis trước đó
b.reshape(1, 5)     # (1,5) - shaped array
# hoặc có thể dùng b[np.newaxis, :]
""" (3, 5), (5,) ở đây tính theo axis=-1 cho dễ. a có thêm axis phía trước nên mình
thêm axis phía trước cho thằng b"""

' (3, 5), (5,) ở đây tính theo axis=-1 cho dễ. a có thêm axis phía trước nên mình\nthêm axis phía trước cho thằng b'

In [4]:
c = a + b   # c.shape = (3, 5)
c

"""
    a có shape (3. 5)
    b có shape (1, 5)
    Dimension 1 của b có thể lặp lại nhiều lần để khớp mà không cần copy data
"""

'\n    a có shape (3. 5)\n    b có shape (1, 5)\n    Dimension 1 của b có thể lặp lại nhiều lần để khớp mà không cần copy data\n'

In [5]:
# Cách bên dưới tương dương nhưng có copy data (thêm vùng nhớ mới)
b = np.ones((5,))
tmp_b = b.reshape(1, 5)
tmp_b_repeadt = tmp_b.repeat(3, axis=0)     # lặp theo axis=0, theo hàng
c = a + tmp_b_repeadt
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [6]:
# Một ví dụ khác
a = np.ones((4, 1))
b = np.ones(3,)

"""
    (3,) => (1, 3)
    (4, 1) => (4, 3)
    (1, 3) => (4, 3)
"""
c = a + b
c.shape

(4, 3)

In [ ]:
a = np.ones((3, 4))
b = np.ones(3, )

c = a + b

""" 
    Báo lỗi: operands could not be broadcast together with shapes (3,4) (3,) 
    (3,) => (1, 3) nhớ 3 đang ở axis cuối thì vẫn ở cuối
    Không thể lặp lại b để khớp với a được.
"""

In [10]:
# Thêm ví dụ cho trường hợp có nhiều dimension
a = np.ones((3, 4, 5))
b = np.ones((5,)) 
# b = np.ones((2,))     # báo lỗi 

c = a + b
c

"""
    (5,) => (1, 1, 5)   # 5 vẫn ở axis cuối nhé
    (3, 4, 5)
    lặp lại (1, 1, 5) => (3, 4, 5)
"""

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [12]:
# Thêm ví dụ dimensions nữa phức tạp hơn
a = np.ones((3, 4, 5))
b = np.ones((4, 1))
c = a + b

"""
    (4, 1) => (1, 4, 1)     # thêm từ bên trái
    (1, 4, 1) => (3, 4, 1) => (3, 4, 5)     # chưa rõ lặp lại theo chiều nào trước
    đơn giản nhận thấy (4, 1) = > (4, 5) lặp lại cột 5 lần
    (1, 4, 5) => (3, 4, 5) lặp lại cả ma trận 3 lần được theo depth
"""

## Setting array elements

In [20]:
a = np.arange(10)
a.dtype

dtype('int64')

In [21]:
# np array chứa các phần tử có cùng dữ liệu khi khởi tạo
# Cần chú ý khi thêm các giá trị có kiểu dữ liệu khác nó sẽ chuyển về kiểu dữ liệu ban đầu
a[5] = 7.8  # a ban đầu có dtype là int64
a 

array([0, 1, 2, 3, 4, 7, 6, 7, 8, 9])

In [22]:
a.fill(-5.8)    # nó vẫn huyển về dtype='int64
a

array([-5, -5, -5, -5, -5, -5, -5, -5, -5, -5])

In [23]:
# đặt dtype ngay khi khởi tạo
a = np.array([1,2, 3], dtype=np.float32)
a.dtype

dtype('float32')

In [24]:
a = np.array([1, 0, 0, 1], dtype=bool)  # kiểu boolean
a.dtype
a

array([ True, False, False,  True])